image: alpine:latest

before_script:
  - apk add build-base cmake git gtest doxygen graphviz freetype tcl tk
  - apk add freeimage openssh --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/

stages:
  - build
  - test

build:
  stage: build
  script:
    - cmake -B buildDir -S .
    - cmake --build buildDir

test:
  stage: test
  script:
    - cmake --build buildDir --target test
  dependencies:
    - build
